---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ffxiv-item-name-database-resources

Resources:
  ItemDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: Number
  
  SsmParameterItemDataTable:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref ItemDataTable
      Name: /ffxiv-item-name-database/item-data-table-name

  AlertSnsTopic:
    Type: AWS::SNS::Topic

  SsmParameterAlertSnsTopic:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref AlertSnsTopic
      Name: /ffxiv-item-name-database/alert-sns-topic

  SSMParameterHostName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: ffxiv-itndb.luciferous.xyz
      Name: /ffxiv-item-name-database/api-host-name

  APIHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !GetAtt SSMParameterHostName.Value

Outputs:
  ItemDataTableName:
    Value: !Ref ItemDataTable

  SsmParameterNameItemDataTable:
    Value: !Ref SsmParameterItemDataTable

  AlertSnsTopicArn:
    Value: !Ref AlertSnsTopic

  SsmParameterNameAlertSnsTopic:
    Value: !Ref SsmParameterAlertSnsTopic

  SsmParameterNameHostName:
    Value: !Ref SSMParameterHostName

  APIHostZoneNameServers:
    Value: !Join ["; ", !GetAtt APIHostedZone.NameServers]
