---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ffxiv-item-name-database-resources

Resources:
  ItemDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: Number

Outputs:
  ItemDataTableName:
    Value: !Ref ItemDataTable
